[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
webdex_factory = "CVo61LAJcaB6BZ5oScydhG6nAnL7RPrU27EJ39uzUYuc"
webdex_manager = "6RuoSrSkzbTyMTdVzXp1xn2gyH4h9FtdZ8iQa12jmZqp"
webdex_payments = "AVHdHmVQS5r9s4rq8D5XdkVmD97hXkvGzpeau2idxkL1"
webdex_strategy = "BW8NiUW7jpcKmwFtBLVdgBwxNA4QR5CydPbKWb5oSkna"
webdex_sub_accounts = "9tgvAbnsLUZ78v5C8HzaYVZhTuPk5JqX9G2tSVjdVMYL"
webdex_network = "CFGdoedbnF9ar7WaEvubtSmXpoTx8o3CpafhAdsVCuhK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"