[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
webdex_factory = "CVo61LAJcaB6BZ5oScydhG6nAnL7RPrU27EJ39uzUYuc"
webdex_manager = "CnMdKapFgFEuxcKoy8WRNmp6QfENE2hHtZXyBwnf7yLH"
webdex_network = "EXRdumfXfTUH5NrzhLfJCAcGtNp9UtgjtvBwfh4WpXtE"
webdex_payments = "6zbeWoZkQ6mnrzm878ii246BHPyiqVxmaMekRdWNL2h5"
webdex_strategy = "418sMdM3mq48AdsMgNpt6gNp6q3vNNcyUB3THzqQmSgH"
webdex_sub_accounts = "D4KYax2aKb7a3zexPXvkuvn5SWij2SLyftdFgF9N8Eje"

[programs.devnet]
webdex_factory = "CVo61LAJcaB6BZ5oScydhG6nAnL7RPrU27EJ39uzUYuc"
webdex_manager = "CnMdKapFgFEuxcKoy8WRNmp6QfENE2hHtZXyBwnf7yLH"
webdex_network = "EXRdumfXfTUH5NrzhLfJCAcGtNp9UtgjtvBwfh4WpXtE"
webdex_payments = "6zbeWoZkQ6mnrzm878ii246BHPyiqVxmaMekRdWNL2h5"
webdex_strategy = "418sMdM3mq48AdsMgNpt6gNp6q3vNNcyUB3THzqQmSgH"
webdex_sub_accounts = "D4KYax2aKb7a3zexPXvkuvn5SWij2SLyftdFgF9N8Eje"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"