[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
webdex_factory = "6LaJ7n5DXTn4ntXb75JKqJZJsku3QHBPjiNAmjsdFi2i"
webdex_manager = "EcVT3zGP8uC7bYtDEXks43b7tQ219KUCq8XvsCbdq1gQ"
webdex_network = "66E8D8LRoAwze5aAURujjiKgMMFDejZADFzoX8sRSBwp"
webdex_payments = "8Hd3LCFZz5K73YKLCenJWr29n8G7spym67esV1honot4"
webdex_strategy = "FiogR2EQUviZr5zNZPjCkid27HshpEdRZyfjuGKH1Q8a"
webdex_sub_accounts = "FG9xLyLYu7sjMFJDhBWFRtaYB33yrQeFx7JGb2EmFGF6"

[programs.devnet]
webdex_factory = "6LaJ7n5DXTn4ntXb75JKqJZJsku3QHBPjiNAmjsdFi2i"
webdex_manager = "EcVT3zGP8uC7bYtDEXks43b7tQ219KUCq8XvsCbdq1gQ"
webdex_network = "66E8D8LRoAwze5aAURujjiKgMMFDejZADFzoX8sRSBwp"
webdex_payments = "8Hd3LCFZz5K73YKLCenJWr29n8G7spym67esV1honot4"
webdex_strategy = "FiogR2EQUviZr5zNZPjCkid27HshpEdRZyfjuGKH1Q8a"
webdex_sub_accounts = "FG9xLyLYu7sjMFJDhBWFRtaYB33yrQeFx7JGb2EmFGF6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"