[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
webdex_factory = "6LaJ7n5DXTn4ntXb75JKqJZJsku3QHBPjiNAmjsdFi2i"
webdex_manager = "2ybNsGNJiEmDT3gkX3Tbm4ewdrfxRZS7gvd9Ff3gZFj6"
webdex_network = "66E8D8LRoAwze5aAURujjiKgMMFDejZADFzoX8sRSBwp"
webdex_payments = "24xr25kWdRkLFZTfsxjrpyQWfezn3Eof65VaM9D7FXiy"
webdex_strategy = "FiogR2EQUviZr5zNZPjCkid27HshpEdRZyfjuGKH1Q8a"
webdex_sub_accounts = "2dCrz8q5LcBcc3zmVq7GcLT8Ud9R2FtmLCgWxFvAhyo6"

[programs.devnet]
webdex_factory = "6LaJ7n5DXTn4ntXb75JKqJZJsku3QHBPjiNAmjsdFi2i"
webdex_manager = "2ybNsGNJiEmDT3gkX3Tbm4ewdrfxRZS7gvd9Ff3gZFj6"
webdex_network = "66E8D8LRoAwze5aAURujjiKgMMFDejZADFzoX8sRSBwp"
webdex_payments = "24xr25kWdRkLFZTfsxjrpyQWfezn3Eof65VaM9D7FXiy"
webdex_strategy = "FiogR2EQUviZr5zNZPjCkid27HshpEdRZyfjuGKH1Q8a"
webdex_sub_accounts = "2dCrz8q5LcBcc3zmVq7GcLT8Ud9R2FtmLCgWxFvAhyo6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"